name: Security Checks

on:
  merge_group:
    types: [checks_requested]
  pull_request:
  schedule:
    - cron: '10 5 * * 6'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  Scans:
    name: Scans
    uses: ncino/security-checks/.github/workflows/security-checks.yml@v8.2
    with:
      trufflehog_ignore_list: >-
        spec/lib/ncino.zip,
        src/LLC_BI/main/default/staticresources/llc_web_ui/LiveEditor/scripts/common/webimage.htm,
        src/staticresources/llc_web_ui.resource,
        staticresources/llc_web_ui.resource
    secrets: inherit
